name: the_note_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter_staggered_grid_view: 0.6.1
  intl: 0.17.0
  floor_annotation: any
  floor: any
  rxdart: 0.27.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  floor_generator: any
  build_runner: any

flutter: 
  uses-material-design: true

